/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LukesMightyGif {
        "controls": boolean;
        "currentTime": number;
        "duration": number;
        "height": number;
        "paused": boolean;
        "playbackRate": number;
        "src": string;
        /**
          * The next few props are meant to be treated as read-only. I don't know how to make them read-only in Stencil, so this is all you get 🤷‍♂️.
         */
        "width": number;
    }
}
export interface LukesMightyGifCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLukesMightyGifElement;
}
declare global {
    interface HTMLLukesMightyGifElement extends Components.LukesMightyGif, HTMLStencilElement {
    }
    var HTMLLukesMightyGifElement: {
        prototype: HTMLLukesMightyGifElement;
        new (): HTMLLukesMightyGifElement;
    };
    interface HTMLElementTagNameMap {
        "lukes-mighty-gif": HTMLLukesMightyGifElement;
    }
}
declare namespace LocalJSX {
    interface LukesMightyGif {
        "controls"?: boolean;
        "currentTime"?: number;
        "duration"?: number;
        "height"?: number;
        "onOncanplay"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onOncanplaythrough"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onOndurationchange"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onOnerror"?: (event: LukesMightyGifCustomEvent<Error>) => void;
        "onOnload"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onOnloadedmetadata"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onOnloadstart"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onOnprogress"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "paused"?: boolean;
        "playbackRate"?: number;
        "src"?: string;
        /**
          * The next few props are meant to be treated as read-only. I don't know how to make them read-only in Stencil, so this is all you get 🤷‍♂️.
         */
        "width"?: number;
    }
    interface IntrinsicElements {
        "lukes-mighty-gif": LukesMightyGif;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lukes-mighty-gif": LocalJSX.LukesMightyGif & JSXBase.HTMLAttributes<HTMLLukesMightyGifElement>;
        }
    }
}
