/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LukesMightyGif {
        /**
          * Whether or not to show the controls. Defaults to true.
         */
        "controls": boolean;
        /**
          * The current time in milliseconds. Defaults to 0. Setting this value will seek to the provided time.
         */
        "currentTime": number;
        /**
          * The duration of the gif. Defaults to 0. Read-only.
         */
        "duration": number;
        /**
          * The height of the gif. Defaults to 0. Read-only.
         */
        "height": number;
        /**
          * Whether or not the gif is paused. Defaults to true.
         */
        "paused": boolean;
        /**
          * How fast the gif should play in multiples of the base speed. Defaults to 1.
         */
        "playbackRate": number;
        "src": string;
        /**
          * The width of the gif. Defaults to 0. Read-only.
         */
        "width": number;
    }
}
export interface LukesMightyGifCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLukesMightyGifElement;
}
declare global {
    interface HTMLLukesMightyGifElement extends Components.LukesMightyGif, HTMLStencilElement {
    }
    var HTMLLukesMightyGifElement: {
        prototype: HTMLLukesMightyGifElement;
        new (): HTMLLukesMightyGifElement;
    };
    interface HTMLElementTagNameMap {
        "lukes-mighty-gif": HTMLLukesMightyGifElement;
    }
}
declare namespace LocalJSX {
    interface LukesMightyGif {
        /**
          * Whether or not to show the controls. Defaults to true.
         */
        "controls"?: boolean;
        /**
          * The current time in milliseconds. Defaults to 0. Setting this value will seek to the provided time.
         */
        "currentTime"?: number;
        /**
          * The duration of the gif. Defaults to 0. Read-only.
         */
        "duration"?: number;
        /**
          * The height of the gif. Defaults to 0. Read-only.
         */
        "height"?: number;
        "onCanplay"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onCanplaythrough"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onDurationchange"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onError"?: (event: LukesMightyGifCustomEvent<Error>) => void;
        "onLoad"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onLoadedmetadata"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onLoadstart"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onPause"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onPlay"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onProgress"?: (event: LukesMightyGifCustomEvent<any>) => void;
        "onSeeked"?: (event: LukesMightyGifCustomEvent<any>) => void;
        /**
          * Whether or not the gif is paused. Defaults to true.
         */
        "paused"?: boolean;
        /**
          * How fast the gif should play in multiples of the base speed. Defaults to 1.
         */
        "playbackRate"?: number;
        "src"?: string;
        /**
          * The width of the gif. Defaults to 0. Read-only.
         */
        "width"?: number;
    }
    interface IntrinsicElements {
        "lukes-mighty-gif": LukesMightyGif;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lukes-mighty-gif": LocalJSX.LukesMightyGif & JSXBase.HTMLAttributes<HTMLLukesMightyGifElement>;
        }
    }
}
